services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./_docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    depends_on:
      - app

  app:
    build:
      context: .
      dockerfile: _docker/Dockerfile
      args:
        USER_UID: ${USER_UID:-1000}
        USER_GID: ${USER_GID:-1000}
    user: "${USER_UID:-1000}:${USER_GID:-1000}"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      DB_HOST: db
      DB_DATABASE: laravel
      DB_USERNAME: laravel
      DB_PASSWORD: secret

  db:
    image: postgis/postgis:15-3.3
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    volumes:
      - postgis_data:/var/lib/postgresql/data

volumes:
  postgis_data: